[package]
name = "vcvrack-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"   # Updated to latest stable version
egui = "0.30.0"     # Updated to match eframe version

[target.'cfg(windows)'.dependencies]
windows = "0.51"